[mux]
name        = 'mux0'
chip        = 'CD74HC4067M'
com         = 'GP22'
s_0         = 'GP21'
s_1         = 'GP20'
s_2         = 'GP19'
s_3         = 'GP18'

[rows]
send        = true
row_1       = 'GP0'
row_2       = 'GP1'
row_3       = 'GP2'
row_4       = 'GP3'
row_5       = 'GP4'
row_6       = 'GP5'
row_7       = 'GP6'

[columns]
mux         = 'mux0'
col_1       = 0
col_2       = 1
col_3       = 2
col_4       = 3
col_5       = 4
col_6       = 5
col_7       = 6
col_8       = 7
col_9       = 8

# key addresses are listed as [row,column]
# [3,4] would be row 3, column 4

[encoder_0]
# thumb
name        = 'e0'
pin_A       = 'GP28'
pin_B       = 'GP27'
switch      = [7,7]

[encoder_1]
# top inside
name         = 'e1'
pin_A       = 'GP2'
pin_B       = 'GP13'
switch      = [1,9]

[encoder_2]
# outside
name        = 'e2'
pin_A       = 'GP14'
pin_B       = 'GP15'
switch      = [1,2]

[neopixel]
type        = 'sk6812'
data        = 'GP7'

[i2c]
scl         = 'GP17'
sda         = 'GP16'

